version: "3.6"
services:

#books
  app:
    build: 
      context: ./books
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8000:5000"
    volumes:
      - .:/books/app
    links:
      - db
  db:
    image: mongo:4.0.27
    hostname: library_db
    environment:
      - MONGO_INITDB_DATABASE=library_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017



 #customer
  mysql:
      image: mysql:8
      container_name: customer-db
      command: --default-authentication-plugin=mysql_native_password      
      environment:
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_DATABASE: mysql
        MYSQL_ROOT_PASSWORD: mysql
      restart: always
      ports:
        - 3306:3306

volumes: 
  mongodb_data: {}
