version: "3.6"
services:

#books
  app:
    build: 
      context: ./books
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8000:5000"
    volumes:
      - .:/books/app
    links:
      - db
  db:
    image: mongo:4.0.27
    hostname: library_db
    environment:
      - MONGO_INITDB_DATABASE=library_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017



 #customer
  mysql:
      image: mysql:8
      container_name: customer-db
      command: --default-authentication-plugin=mysql_native_password      
      environment:
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_DATABASE: mysql
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - dbdata:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306

  app_customer:
    build: 
      context: ./customer
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8001:5001"
    volumes:
      - .:/customer/app
    links:
      - mysql
  #borrowing
  app_borrowing:
    build: 
      context: ./borrowing
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8002:5002"
    volumes:
      - .:/borrowing/app
    links:
      - mysql



  #notification service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes: 
  mongodb_data: {}
  dbdata: {}
  
