version: "3.6"
services:
  app:
    build: 
      context: ./books
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8000:5000"
    volumes:
      - .:/books/app
    links:
      - db
  db:
    image: mongo:4.0.27
    hostname: library_db
    environment:
      - MONGO_INITDB_DATABASE=library_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017


volumes: 
  mongodb_data: {}
